apiVersion: v1
kind: Service
metadata:
  name: ai-webapp
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: ai-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081

